### ISSUE TITLE
Auto-expand directory in the tree when new file created

### ISSUE THREAD

**Issue by metanet** [hakanu/pervane#124] opened 2020-06-17 20:18 UTC
When a new file is created in a directory and that directory is not expanded in the navigation tree, pervane doesn't expand the directory in the navigation tree. So we need to click on the directory to see the new file. I think it would be handy if the directory is automatically expanded in the navigation tree.

**Comment by hakanu** [comment] 2020-06-18 09:39
Duplicate of #42

**Closed by hakanu** 2020-06-18 09:39 UTC
Labels: duplicate, enhancement
