### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_user'

### ISSUE THREAD

**Issue by ianrego** [hakanu/pervane#163] opened 2023-02-03 18:59 UTC
Hello! 

I'm trying to run pervane in a virtual environment and I'm getting this error:

(env) admin@george-Baytrial-Platform:~/app/pervane/pervane$ python3 pervane/serve.py --init
Traceback (most recent call last):
  File "/home/admin/app/pervane/pervane/pervane/serve.py", line 55, in <module>
    from flask_user import current_user, login_required, UserManager, UserMixin
ModuleNotFoundError: No module named 'flask_user'

Would you have any suggestions?

**Comment by hakanu** [comment] 2023-02-04 13:13
This is duplicate of #162 which is fixed.

**Closed by hakanu** 2023-02-04 13:13 UTC
